version: '3'
services:
  file-server:
    build: ./go-file-server/
    ports:
      - "9999:9999"
    volumes:
      - maeumgagym_video-data:/app/videos
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      BASE_URL: ${BASE_URL}
    restart: always
  ffmpeg-app:
    build: ./ffmpeg-app/
    volumes:
      - maeumgagym_video-data:/app/videos
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      BASE_URL: ${BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
    restart: always
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  maeumgagym_video-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.103,rw
      device: :/Users/student/maeumgaGym