version: '3'
services:
  file-server:
    build: ./go-file-server/ 
    ports:
      - "9999:9999"
    volumes:
      - video-data:/app/videos
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      BASE_URL: ${BASE_URL}
      SECRET_TOKEN: ${SECRET_TOKEN}
    restart: always
  ffmpeg-app:
    build: ./ffmpeg-app/
    volumes:
      - video-data:/app/videos
      - db-data:/app/db
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      BASE_URL: ${BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
    restart: always
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  video-data:
  db-data:
