version: '3'
services:
  file-server:
    build: ./go-file-server/ 
    ports:
      - "9999:9999"
    volumes:
      - video-data:/app/videos
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      BASE_URL: ${BASE_URL}
      SECRET_TOKEN: ${SECRET_TOKEN}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
    restart: always
  ffmpeg-app:
    build: ./ffmpeg-app/
    volumes:
      - video-data:/app/videos
      - db-data:/app/db
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      BASE_URL: ${BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
    restart: always
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
volumes:
  video-data:
  db-data:
